spring.application.name=DataJPA_CLR
#spring.datasource.url=jdbc:h2:mem:practice
#spring.jpa.show-sql=true
spring.mvc.view.prefix=/WEB-INF/pages/
spring.mvc.view.suffix=.jsp
spring.datasource.url=jdbc:mysql://localhost:3306/db_j2ee
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true